name: CI (cann)

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - master
    paths: [
      '.github/workflows/build-cann.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp'
    ]

  pull_request:
    types: [opened, synchronize, reopened]
    paths: [
      '.github/workflows/build-cann.yml',
      'ggml/src/ggml-cann/**'
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  openEuler-latest-cann:
    runs-on: linux-aarch64-a2-1
    container:
      image: swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.5.0-910b-openeuler24.03-py3.11
    strategy:
      matrix:
        use_acl_graph: ['on', 'off']
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          yum install -y --setopt=install_weak_deps=False --setopt=tsflags=nodocs \
            git gcc gcc-c++ make cmake openssl-devel
          yum clean all && rm -rf /var/cache/yum
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        env:
          BUILD_TYPE: Release
          USE_ACL_GRAPH: ${{ matrix.use_acl_graph }}
        run: |
          source /usr/local/Ascend/ascend-toolkit/set_env.sh --force
          cmake -S . -B build \
              -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
              -DGGML_CANN=on \
              -DUSE_ACL_GRAPH=${USE_ACL_GRAPH}
          cmake --build build -j $(nproc)
